# CMake generated Testfile for 
# Source directory: /home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests
# Build directory: /home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(StringParser.UltraBasic "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.UltraBasic")
add_test(StringParser.BlankLine "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.BlankLine")
add_test(StringParser.OneRemStart "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.OneRemStart")
add_test(StringParser.TwoRemStart "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.TwoRemStart")
add_test(StringParser.OneRemBack "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.OneRemBack")
add_test(StringParser.SimpleAddition "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.SimpleAddition")
add_test(StringParser.QuadAddition "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.QuadAddition")
add_test(StringParser.NestedAddition "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.NestedAddition")
add_test(StringParser.MultiNestedAddition "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.MultiNestedAddition")
add_test(StringParser.NoopSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.NoopSubtraction")
add_test(StringParser.SimpleSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.SimpleSubtraction")
add_test(StringParser.MultiCharSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.MultiCharSubtraction")
add_test(StringParser.InnerTextSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.InnerTextSubtraction")
add_test(StringParser.RepeatedTextSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.RepeatedTextSubtraction")
add_test(StringParser.NestedSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.NestedSubtraction")
add_test(StringParser.MultiNestedSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.MultiNestedSubtraction")
add_test(StringParser.NestedSubtraction2 "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.NestedSubtraction2")
add_test(StringParser.Example1 "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.Example1")
add_test(StringParser.Example2 "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.Example2")
add_test(StringParser.Example3 "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.Example3")
add_test(StringParser.GeneralMix "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.GeneralMix")
add_test(StringParser.NestedParenthesis "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.NestedParenthesis")
add_test(StringParser.UnaryBinaryPrecedence "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.UnaryBinaryPrecedence")
add_test(StringParser.Multiline "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.Multiline")
add_test(StringParser.NoParenthesis "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParser.NoParenthesis")
add_test(StringParserMalformed.Capitals "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.Capitals")
add_test(StringParserMalformed.MixedOperators "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.MixedOperators")
add_test(StringParserMalformed.MultipleSubtraction "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.MultipleSubtraction")
add_test(StringParserMalformed.NoParenthesisAddition "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.NoParenthesisAddition")
add_test(StringParserMalformed.ExtraOperators "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.ExtraOperators")
add_test(StringParserMalformed.Example1 "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.Example1")
add_test(StringParserMalformed.Example2 "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.Example2")
add_test(StringParserMalformed.Example3 "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.Example3")
add_test(StringParserMalformed.RemoveAtEndOfString "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.RemoveAtEndOfString")
add_test(StringParserMalformed.MissingParen "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.MissingParen")
add_test(StringParserMalformed.NestedParensWithoutOperator "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.NestedParensWithoutOperator")
add_test(StringParserMalformed.ExtraParen "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.ExtraParen")
add_test(StringParserMalformed.Smiley "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserMalformed.Smiley")
add_test(StringParserStress.LargeString "/home/cs104/cs104hw/hw-jesalisb/hw3/hw3_check/stringparser_tests/stringparser_tests" "--gtest_filter=StringParserStress.LargeString")
