#include "amazon_checker.h"

#include "Utility.h"
#include "DatabaseParser.h"
#include "ConsoleParser.h"

#include <gtest/gtest.h>

TEST(AmazonSorting, ByRating)
{
    std::string const commands =
            "OR r Abstraction The Shirt\n"
            "QUIT database.out\n";

    std::string const expectedOutput =
            "Read 3 products\n"
            "Read 2 users\n"
            "=====================================\n"
            "Menu: \n"
            "  AND term term ...                  \n"
            "  OR term term ...                   \n"
            "  ADD username search_hit_number     \n"
            "  VIEWCART username                  \n"
            "  BUYCART username                   \n"
            "  QUIT new_db_filename               \n"
            "====================================\n"
            "\n"
            "Enter command: \n"
            "Hit   1\n"
            "The Killer Rabbit of Caerbannog: A Documentary         \n"
            "Genre: Disaster Rating: PG-13\n"
            "0.01 800000 left.\n"
            "Rating: 5.0\n"
            "\n"
            "Hit   2\n"
            "Men's Fitted Shirt\n"
            "Size: Medium Brand: J. Crew\n"
            "39.99 25 left.\n"
            "Rating: 3.5\n"
            "\n"
            "Hit   3\n"
            "Data Abstraction\n"
            "Author: Carrano ISBN: 978-013292372-9\n"
            "79.99 20 left.\n"
            "Rating: 3.00\n"
            "\n"
            "\n"
            "Enter command: ";


    std::string const inputDatabase =
            "<products>\n"
            "book\n"
            "Data Abstraction\n"
            "79.99\n"
            "20\n"
            "978-013292372-9\n"
            "Carrano\n"
            "movie\n"
            "The Killer Rabbit of Caerbannog: A Documentary\n"
            "0.01\n"
            "800000\n"
            "Disaster\n"
            "PG-13\n"
            "clothing\n"
            "Men's Fitted Shirt\n"
            "39.99\n"
            "25\n"
            "Medium\n"
            "J. Crew\n"
            "</products>\n"
            "<users>\n"
            "jdoe 100.0 0\n"
            "fjones 100.0 0\n"
            "</users>\n"
            "<reviews>\n"
            "Data Abstraction\n"
            "3 jdoe 2000-01-01 Too abstract.\n"
            "Men's Fitted Shirt\n"
            "3 fjones 2007-09-04 Way too tight.\n"
            "Men's Fitted Shirt\n"
            "4 fjones 2016-02-20 Fits well!.\n"
            "The Killer Rabbit of Caerbannog: A Documentary\n"
            "5 jdoe 2016-02-27 Why did the police show up at the end?\n"
            "The Killer Rabbit of Caerbannog: A Documentaryn\n"
            "5 jdoe 2016-02-27 You don't just paint EEERUGH\n"
            "</reviews>";

    EXPECT_TRUE(checkConsoleOutput(commands, inputDatabase, {Menu, Input, Hit, Input}, expectedOutput));
}

TEST(AmazonSorting, ByRating_NoReviews)
{
    std::string const commands =
            "OR r Abstraction And The Shirt\n"
            "QUIT database.out\n";

    std::string const expectedOutput =
            "Read 3 products\n"
            "Read 2 users\n"
            "=====================================\n"
            "Menu: \n"
            "  AND term term ...                  \n"
            "  OR term term ...                   \n"
            "  ADD username search_hit_number     \n"
            "  VIEWCART username                  \n"
            "  BUYCART username                   \n"
            "  QUIT new_db_filename               \n"
            "====================================\n"
            "\n"
            "Enter command: \n"
            "Hit   1\n"
            "The Killer Rabbit of Caerbannog: A Documentary         \n"
            "Genre: Disaster Rating: PG-13\n"
            "0.01 800000 left.\n"
            "Rating: 5.0\n"
            "\n"
            "Hit   2\n"
            "Men's Fitted Shirt\n"
            "Size: Medium Brand: J. Crew\n"
            "39.99 25 left.\n"
            "Rating: 3.5\n"
            "\n"
            "Hit   3\n"
            "Data Abstraction\n"
            "Author: Carrano ISBN: 978-013292372-9\n"
            "79.99 20 left.\n"
            "Rating: 3.00\n"
            "\n"
            "Hit   4\n"
            "Ear and Nose Muffs\n"
            "Size: Large-Head Brand: Crew Cut\n"
            "18.00 100 left.\n"
            "Rating: 0\n"
            "\n"
            "\n"
            "Enter command: ";


    std::string const inputDatabase =
            "<products>\n"
            "book\n"
            "Data Abstraction\n"
            "79.99\n"
            "20\n"
            "978-013292372-9\n"
            "Carrano\n"
            "movie\n"
            "The Killer Rabbit of Caerbannog: A Documentary\n"
            "0.01\n"
            "800000\n"
            "Disaster\n"
            "PG-13\n"
            "clothing\n"
            "Men's Fitted Shirt\n"
            "39.99\n"
            "25\n"
            "Medium\n"
            "J. Crew\n"
            "clothing\n"
            "Ear and Nose Muffs\n"
            "18.00\n"
            "100\n"
            "Large-Head\n"
            "Crew Cut\n"
            "</products>\n"
            "<users>\n"
            "jdoe 100.0 0\n"
            "fjones 100.0 0\n"
            "</users>\n"
            "<reviews>\n"
            "Data Abstraction\n"
            "3 jdoe 2000-01-01 Too abstract.\n"
            "Men's Fitted Shirt\n"
            "3 fjones 2007-09-04 Way too tight.\n"
            "Men's Fitted Shirt\n"
            "4 fjones 2016-02-20 Fits well!.\n"
            "The Killer Rabbit of Caerbannog: A Documentary\n"
            "5 jdoe 2016-02-27 Why did the police show up at the end?\n"
            "The Killer Rabbit of Caerbannog: A Documentaryn\n"
            "5 jdoe 2016-02-27 You don't just paint EEERUGH\n"
            "</reviews>";

    EXPECT_TRUE(checkConsoleOutput(commands, inputDatabase, {Menu, Input, Hit, Input}, expectedOutput));
}

TEST(AmazonSorting, ByName)
{
        std::string const commands =
                "OR n Graveyard Abstraction And The Foo Shirt VHS\n"
                "QUIT database.out\n";

        std::string const expectedOutput =
                "Read 3 products\n"
                "Read 2 users\n"
                "=====================================\n"
                "Menu: \n"
                "  AND term term ...                  \n"
                "  OR term term ...                   \n"
                "  ADD username search_hit_number     \n"
                "  VIEWCART username                  \n"
                "  BUYCART username                   \n"
                "  QUIT new_db_filename               \n"
                "====================================\n"
                "\n"
                "Enter command: \n"
                "Hit   1\n"
                "Data Abstraction\n"
                "Author: Carrano ISBN: 978-013292372-9\n"
                "79.99 20 left.\n"
                "Rating: 3.00\n"
                "\n"
                "Hit   2\n"
                "Ear and Nose Muffs\n"
                "Size: Large-Head Brand: Crew Cut\n"
                "18.00 100 left.\n"
                "Rating: 0\n"
                "\n"
                "Hit   3\n"
                "Graveyard of the Pacific\n"
                "Author: Anthony Dalton ISBN: 978-192661331-4\n"
                "9.95 7 left.\n"
                "Rating: 0.0\n"
                "\n"
                "Hit   4\n"
                "Men's Fitted Shirt\n"
                "Size: Medium Brand: J. Crew\n"
                "39.99 25 left.\n"
                "Rating: 3.5\n"
                "\n"
                "Hit   5\n"
                "Planet Earth VHS\n"
                "Genre: Documentary Rating: PG\n"
                "20.25 4 left.\n"
                "Rating: 0\n"
                "\n"
                "Hit   6\n"
                "The Killer Rabbit of Caerbannog: A Documentary         \n"
                "Genre: Disaster Rating: PG-13\n"
                "0.01 800000 left.\n"
                "Rating: 5.0\n"
                "\n"
                "Hit   7\n"
                "foo\n"
                "Genre: Programming Rating: TV-14\n"
                "20.25 4 left.\n"
                "Rating: 0\n"
                "\n"
                "\n"
                "Enter command: ";


        std::string const inputDatabase =
                "<products>\n"
                "book\n"
                "Data Abstraction\n"
                "79.99\n"
                "20\n"
                "978-013292372-9\n"
                "Carrano\n"
                "movie\n"
                "The Killer Rabbit of Caerbannog: A Documentary\n"
                "0.01\n"
                "800000\n"
                "Disaster\n"
                "PG-13\n"
                "clothing\n"
                "Men's Fitted Shirt\n"
                "39.99\n"
                "25\n"
                "Medium\n"
                "J. Crew\n"
                "movie\n"
                "Planet Earth VHS\n"
                "20.25\n"
                "4\n"
                "Documentary\n"
                "PG\n"
                "clothing\n"
                "Ear and Nose Muffs\n"
                "18.00\n"
                "100\n"
                "Large-Head\n"
                "Crew Cut\n"
                "movie\n"
                "foo\n"
                "20.25\n"
                "4\n"
                "Programming\n"
                "TV-14\n"
                "book\n"
                "Graveyard of the Pacific\n"
                "9.95\n"
                "7\n"
                "978-192661331-4\n"
                "Anthony Dalton\n"
                "</products>\n"
                "<users>\n"
                "jdoe 100.0 0\n"
                "fjones 100.0 0\n"
                "</users>\n"
                "<reviews>\n"
                "Data Abstraction\n"
                "3 jdoe 2000-01-01 Too abstract.\n"
                "Men's Fitted Shirt\n"
                "3 fjones 2007-09-04 Way too tight.\n"
                "Men's Fitted Shirt\n"
                "4 fjones 2016-02-20 Fits well!.\n"
                "The Killer Rabbit of Caerbannog: A Documentary\n"
                "5 jdoe 2016-02-27 Why did the police show up at the end?\n"
                "The Killer Rabbit of Caerbannog: A Documentaryn\n"
                "5 jdoe 2016-02-27 You don't just paint EEERUGH\n"
                "</reviews>";

        EXPECT_TRUE(checkConsoleOutput(commands, inputDatabase, {Menu, Input, Hit, Input}, expectedOutput));
}
